[book]
authors = ["Bj√∂rn Quentin", "Sergio Gasquez"]
description = "Embedded Rust (no_std) on Espressif training material"
language = "en"
multilingual = false
src = "src"
title = "Embedded Rust (no_std) on Espressif"

[rust]
edition = "2021"


[output.html]
git-repository-url = "https://github.com/Sergio/no_std-training"
