name: Book CI

on:
  push:
    paths:
      - "training/"
      - "training/**"
      - ".github/workflows/book.yml"
      - "**book**"
  pull_request:
    paths:
      - "training/"
      - "training/**"
      - ".github/workflows/book.yml"
      - "**book**"
  workflow_dispatch:
    paths:
      - "training/"
      - "training/**"
      - ".github/workflows/book.yml"
      - "**book**"

env:
  MDBOOK_VERSION: "0.5.1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - uses: jontze/action-mdbook@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          use-linkcheck: true
          use-mermaid: true

      - name: Build the contents of the book
        run: mdbook build -d ../output/

      - name: Deploy
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
        uses: appleboy/scp-action@v1.0.0
        with:
          host: docs.espressif.com
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_KEY }}
          target: ${{ secrets.PRODUCTION_TARGET }}
          source: "output/"
          strip_components: 1 # remove the prefix, it's already being placed in /projects/rust/no_std-training
          overwrite: true
